apiVersion: v1
kind: Service
metadata:
  name: ismat-fatima-backend
  namespace: todo
spec:
  type: LoadBalancer
  selector:
    app: ismat-fatima-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
